@startuml
skinparam dpi 300
start
:Вычислить хеш-код ключа;
:Привести хеш к размеру таблицы (hash & (size-1));
:Получить начальный индекс;
if (Стратегия == Chaining) then (да)
  :Индекс = начальный индекс;
else (Открытая адресация)
  :i = 0;
  repeat
    :Индекс = (начальный индекс + пробная_функция(i)) & (size-1);
    :i = i + 1;
  repeat while (ячейка занята?) is (да) -> ; // цикл до свободной или до конца
  :Возврат индекса;
endif
stop
@enduml
